/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	rrkv1 "github.com/rrk-dev/hw-client/pkg/apis/rrk/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHelloWorlds implements HelloWorldInterface
type FakeHelloWorlds struct {
	Fake *FakeRrkV1
	ns   string
}

var helloworldsResource = schema.GroupVersionResource{Group: "rrk.com", Version: "v1", Resource: "helloworlds"}

var helloworldsKind = schema.GroupVersionKind{Group: "rrk.com", Version: "v1", Kind: "HelloWorld"}

// Get takes name of the helloWorld, and returns the corresponding helloWorld object, and an error if there is any.
func (c *FakeHelloWorlds) Get(ctx context.Context, name string, options v1.GetOptions) (result *rrkv1.HelloWorld, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(helloworldsResource, c.ns, name), &rrkv1.HelloWorld{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rrkv1.HelloWorld), err
}

// List takes label and field selectors, and returns the list of HelloWorlds that match those selectors.
func (c *FakeHelloWorlds) List(ctx context.Context, opts v1.ListOptions) (result *rrkv1.HelloWorldList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(helloworldsResource, helloworldsKind, c.ns, opts), &rrkv1.HelloWorldList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &rrkv1.HelloWorldList{ListMeta: obj.(*rrkv1.HelloWorldList).ListMeta}
	for _, item := range obj.(*rrkv1.HelloWorldList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested helloWorlds.
func (c *FakeHelloWorlds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(helloworldsResource, c.ns, opts))

}

// Create takes the representation of a helloWorld and creates it.  Returns the server's representation of the helloWorld, and an error, if there is any.
func (c *FakeHelloWorlds) Create(ctx context.Context, helloWorld *rrkv1.HelloWorld, opts v1.CreateOptions) (result *rrkv1.HelloWorld, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(helloworldsResource, c.ns, helloWorld), &rrkv1.HelloWorld{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rrkv1.HelloWorld), err
}

// Update takes the representation of a helloWorld and updates it. Returns the server's representation of the helloWorld, and an error, if there is any.
func (c *FakeHelloWorlds) Update(ctx context.Context, helloWorld *rrkv1.HelloWorld, opts v1.UpdateOptions) (result *rrkv1.HelloWorld, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(helloworldsResource, c.ns, helloWorld), &rrkv1.HelloWorld{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rrkv1.HelloWorld), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHelloWorlds) UpdateStatus(ctx context.Context, helloWorld *rrkv1.HelloWorld, opts v1.UpdateOptions) (*rrkv1.HelloWorld, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(helloworldsResource, "status", c.ns, helloWorld), &rrkv1.HelloWorld{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rrkv1.HelloWorld), err
}

// Delete takes name of the helloWorld and deletes it. Returns an error if one occurs.
func (c *FakeHelloWorlds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(helloworldsResource, c.ns, name, opts), &rrkv1.HelloWorld{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHelloWorlds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(helloworldsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &rrkv1.HelloWorldList{})
	return err
}

// Patch applies the patch and returns the patched helloWorld.
func (c *FakeHelloWorlds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *rrkv1.HelloWorld, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(helloworldsResource, c.ns, name, pt, data, subresources...), &rrkv1.HelloWorld{})

	if obj == nil {
		return nil, err
	}
	return obj.(*rrkv1.HelloWorld), err
}
